spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=library
  username: postgres
  password: postgres

 jpa:
  generate-ddl: false
  hibernate:
   ddl-auto: update
  show-sql: true

logging:
 level:
  root: error