spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/usermanagment
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
   ddl-auto: none
  properties:
   hibernate:
    temp.use_jdbc_metadata_defaults: false
  show-sql: true
logging:
 level:
  root: ERROR